### ISSUE TITLE
Does Arch's multithreading support automatically scheduled based on component types like Unity DOTS?

### ISSUE THREAD

**Issue by TapsJoy** [genaray/Arch#136]
Due to Unity's pricing policies, I'm considering migrating the project to Godot. However, Godot doesn't have an ECS system.

**Comment by genaray** [comment]
Hey thanks for your interest! :)

Well Arch is bare minimum, it does not do everything automatically. Arch features a multithreaded queries, but those work differently. It basically splits the query, processes them on different threads and joins them once finished. However multithreaded queries do not run parallel to each other :)

**Comment by TapsJoy** [comment]
For example, if I have two multithreaded queries (a and b) and one main thread query (c), when I sequentially call a, b, and c, will they execute in order (with b running after a finishes and c running after b)?

**Comment by genaray** [comment]
> For example, if I have two multithreaded queries (a and b) and one main thread query (c), when I sequentially call a, b, and c, will they execute in order (with b running after a finishes and c running after b)?

They are all finished in a row. Only the iteration and what happens in the query is multithreaded. 
So:
```csharp
world.ParallelQuery();   // a
world.ParallelQuery();   // b
world.Query();              // c

First a finishes, then b finishes and then c finishes.
```

The only thing that changes is the way its iterated. It kinda works like [`Parallel.ForEach`](https://learn.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-write-a-simple-parallel-foreach-loop) but without the gc.

```csharp

Example for a parallel query that targets 500 entities on 5 threads.

                          | - Thread 1 processes 100 entities (0-100)
                          | - Thread 2 processes 100entities  (100-200)
ParallelQuery -- | -Thread 3 processes 100 entities (200-...)
                          | - Thread 4 processes 100 entities ...
                          | - Thread 5 processes 100 entities                        
```

A parallel query will block the mainthread and waits for the threads to finish. This is still highly efficient since arch uses a job-system for this. Parallel querys are most effective for high amounts of entities like ten to hundred of thousands... or even millions. Makes most sense for tasks that only target the specific entity it processes, like movement, physics or whatever. More complex stuff needs to be managed/locked yourself :)

**Comment by TapsJoy** [comment]
Thanks buddy. Honestly, this exceeds my expectations. I'm working on a lock-step game, so the sequential execution of multithreaded logic is crucial. I'll try using this framework to migrate my Unity DOTS project to Godot.
