### ISSUE TITLE
CommandBuffer suggestions

### ISSUE THREAD

**Issue by andreakarasho** [genaray/Arch#30]
I found the commandbuffers implementation not very user-friendly and about this I suggest to merge all the cmdbuffer types into an unique `class` (not a `struct`) to emulate the `World` class.
I see multiple advatanges:
- a better and tiny API
- users will work with `Entity` struct only [all the internal changes should be tracked into Arch]

Ugly pseudo code:
```csharp
struct Transform { public Vector3 Position; }

var world = World.Create();
var cmd = new CommandBuffer(world);

var entity = cmd.Create<Transform>();
ref var transform = ref cmd.Get<Transform>(in entity);
transform.X = 20;

world.Query(in query, (in Entity e, ref Transform t) => {
   if (t.Position == Vector3.Zero)
      cmd.Destroy(in e); // will mark the entity as destroyed and next queries will not grab this entity until the real destruction
  else
    --t.X;
   
});

```

**Comment by genaray** [comment]
Currently not at home, looking at it later... Well this would be way better in terms of usage ^^

Any idea on how the data structure may look like ? All ways that come into my mind make heavy use of dictionarys for lookups which is very bad for performance... Thats why i came up with the current solution.

**Comment by genaray** [comment]
## Some thoughts
Merging the 4 different command buffers into one commandbuffer is totally possible and would provide a cleaner API... so lets put that onto our list. In this case we could continue using the existing buffers. 

Would still require manuall playbacks however, since some users may want controll about such "sync" points. 

## Using only `Entity`
Is also possible, but would require a lot of dictionary lookups for certain operations. Which would slow the overall queries and usage. 

Commandbuffers use other internal structures and therefore need to map the `Entity` to their buffer arrays. This makes them fast since no lookups are required. The downside of this is that the usage suffers from it. 

## Outlook
A combined commandbuffer which works on pure `Entity` structs, while it still requires no lookups and a clean API. Also they should still support managed structs. 

We need plenty of ideas for this, since overall this will be a very challenging design task. 
For the first it probably makes the most sense to merge the commandbuffers.

**Comment by andreakarasho** [comment]
The ideal would be to handle changes to the `World` class directly. Maybe an internal `World` instance where you put changes that will be merged when the `Playback` function is called.

(Sorry for the comparision, but i think `flecs` is a good startpoint): https://github.com/SanderMertens/flecs/blob/master/examples/c/systems/mutate_entity/src/main.c#L15-L24

**Comment by genaray** [comment]
> The ideal would be to handle changes by the `World` class directly. Maybe an internal `World` instance where you put changes that will be merged when the `Playback` function is called.
> 
> (Sorry for the comparision, but i think `flecs` is a good startpoint): https://github.com/SanderMertens/flecs/blob/master/examples/c/systems/mutate_entity/src/main.c#L15-L24
> 
> edit: missclicked the `close` button sorry

I took a look at flecs but couldnt find a clean way to implement this into Arch. Flecs embedds this into the world itself, i do not really like this approach since it destroys several programming principles and creates a big dependency. Of course that approach also has some advantages, but i found it way too hard to maintain in the future.

Instead i looked at your sugessted API usage and implemented something on my own. Its still pretty "ugly", not cleaned up and optimized. But the first version already works, its located inside the "feature/command_buffer" branch : https://github.com/genaray/Arch/blob/feature/command_buffer/Arch/Core/CommandBuffer/CommandBuffer.cs

Its usage is similar to your provided API sugestion : 
```csharp
var entity = world.Create(new ComponentType[] {typeof(Transform), typeof(Rotation), typeof(int) });
var bufferedEntity = commandBuffer.Create(new ComponentType[] {typeof(Transform), typeof(Rotation), typeof(int) });
        
commandBuffer.Set(in entity, new Transform{ X = 20, Y = 20});
commandBuffer.Add(in entity, new Ai());
        
commandBuffer.Set(in bufferedEntity, new Transform{ X = 20, Y = 20});
commandBuffer.Add(in bufferedEntity, new Ai());

commandBuffer.Playback();
```

What do you think about it ? :)

**Comment by andreakarasho** [comment]
We can probably cose this due to #35 and #37
