### ISSUE TITLE
Godot engine is not supported by this repo?

### ISSUE THREAD

**Issue by pcloves** [genaray/Arch#43]
Hi, I'm a Godot and C# beginner, In the README.md file, it says as follows:
> - 🚢 _**SUPPORT**_ > Supports .NetStandard 2.1, .Net Core 6 and 7 and therefore you may use it with Unity or Godot!

However, I found there are some C# 11 syntaxes, like this (using the `scoped` keyword):
https://github.com/genaray/Arch/blob/b08cc536cd8bda035acad1e0d42a935d3f45ded5/Arch/Core/Archetype.cs#L200-L204

As far as I know, the newest [Godot 4.0](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-1) support only .Net 6.0 and C# 10:

> With the move to .NET 6, users can now target a newer framework that brings optimizations and new APIs. With .NET 6, projects use C# 10 by default and all features are available.

Does it mean the Godot engine is not supported by this project?

**Comment by genaray** [comment]
Great question ! 

Well the language version is actually backward compatible, C# 11 will emit slightly different he IL code. 

However since godot supports .NET 6 this is no iusse. NET 6 will translate the IL Code and doesnt care if it was generated using C#11 or C#10. 

Just make sure you use the nugget package and no copy of the source code ^^

**Comment by pcloves** [comment]
I got it, thanks.

**Comment by genaray** [comment]
> I got it, thanks.

Great to hear ! :) Let me know if you need more help or support.
