### ISSUE TITLE
Sorting entities

### ISSUE THREAD

**Issue by stgeorge** [genaray/Arch#48]
Great library! I ditched my naive one and used this and tripled the raw frame rate.

I'd like to get a set of entities sorted by their Y position to draw them back to front, is there a performant way to do this?

**Comment by genaray** [comment]
Thanks a lot ! :) 

Well theres no inbuild mechanism right now, but i totally see the iusse here.

You could theoretically sort it by acessing the internals of world, archetype and chunk.
However this is kinda annoying and difficult.

Im looking into how other ecs solve this problem, probably we need some way of registering a sorting unit that automaticly takes care of this :)

**Comment by stgeorge** [comment]
Thanks for looking into this, I did end up doing a GetEntities, just felt a little hairy having to get the position component to sort by it - I also looked into getting the efficient iterators example to get the iterator of position components so I could quickly get the Y component in one shot, but didn't see a clean way to tie that sorted list to another array of sprite components. Maybe if I could get back an array of a ValueTuple of 2 components in one shot? Not sure if that'd still kill perf or not.

**Comment by genaray** [comment]
> Maybe if I could get back an array of a ValueTuple of 2 components in one shot?

That would be the better alternative i guess :) 
Like : `public List<References<Sprite,Position>> SortedList;` which you put in `entity.Get<Sprite,Position>()` calls :) 
This would make it a bit clearer and optimizes the calls themself since only one lookup per entity is required.

But as you said it would be smoother if there's a way to receive the actuall arrays in one shot... this could be a new API proposal : `world.Query(in desc, out var positionArray out var spriteArray);` or something similar. 



> efficient iterators example

Do you mean the new API #39 `foreach(var references in world.Query(desc).GetIterator<Position, Sprite>())` ? 
I actually thought i might remove them again since they are slow. Theres no way to make them faster since c# enumerators themself suck, they cause a lot of address jumping ^^ But if they are useful i let them stay.

**Comment by stgeorge** [comment]
Thanks again! I will leave it up to you if you want to do anything with this one - I have the workaround and some ideas to play around with, so the issue could be considered resolved for me. If you add something new then awesome, otherwise I'm already able to push a lot more entities with this library than before, so I'm good.
