### ISSUE TITLE
`in Entity` vs `ref Entity` in `Query()` overloads

### ISSUE THREAD

**Issue by nathanrw** [genaray/Arch#69]
Hi, I managed to shoot myself in the foot earlier and it took me a little while to work out what I had done wrong.

## Bad

```C#
            var qd = QueryDescription().WithAll<MyComponent>();
            World.Query(qd, (ref Entity e, ref MyComponent c) =>
            {
                // Do something
            });
```

This code crashes inside Arch with an access violation.

## Good

```C#
            var qd = QueryDescription().WithAll<MyComponent>();
            World.Query(qd, (in Entity e, ref MyComponent c) =>
            {
                // Do something
            });
```

This code works.

This issue is that in the 'bad' example, the lambda is a `ForEach` and so `Entity` is actually treated as a component type, and naturally there are no such components.

In the 'good' example, the lambda is a `ForEachWithEntity` so it works as expected. But the only difference is `in Entity` vs `ref Entity`. I wonder if something could be done to catch the problem case?

**Comment by genaray** [comment]
Hey there! :) 
Thanks for using Arch btw! 

Well this one is actually a bit of a code smell. There two reasons for this design:
1. `Entity` should never be modified by the User, therefore it needs to be `In`. Otherwise, the user may modify it and that causes undefined behavior.
2. Lambdas and delegates are very restrictive. Unfortunately, they must be predefined/hardcoded and therefore do not allow any variety of their `RefKinds` (in, ref, out...). 

So the API can not be "fixed" to make perfect sense, since the way of how lambdas work. However, we could actually "catch" that case by using `Debug.Asserts` to notify the user that what he's doing is wrong :) 

To get rid of that problem, i suggest to use https://github.com/genaray/Arch.Extended and its source generator. This way you are able to define your queries in a more detailed manner:

```csharp
[Query]
[All<....>, Any<...>, None<...>]
public void MoveEntities([Data] float time, in Entity entity, ref Position position, in Velocity vel){  // Entity can also be removed or be placed wherever you want
   ...
}
```

**Comment by nathanrw** [comment]
Thanks!
