### ISSUE TITLE
Replace Dictionary EntityInfo with a simple array.

### ISSUE THREAD

**Issue by Donaut** [genaray/Arch#70]
Currently, in the code, you have a [EntityInfo property](https://github.com/genaray/Arch/blob/master/src/Arch/Core/World.cs#L158) which is a dictionary but you can make it into an array because all the entities ids just increasing numbers starting from 0. So if you have an entity with an id 5 it can be inside the array at index 5. I'm planning to make a pull request about this, but the array resize logic needs to live somewhere should I place an EnsureCapacity method inside the World class or have an Array Wrapper?

**Comment by genaray** [comment]
Totally agree with you here :) and glad for every help, currently pretty busy with my bachelor thesis.

Just two small Requirements:
- Should be within a Wrapper 
- Should be a jagged array, each bucket size about 16kb (to fit each array acess into l1 cache and increase performance when trimming e.g.)

**Comment by Donaut** [comment]
I don't understand how iterating over many small arrays is faster than a single large array. Or do you want to use chunks because then it's possible to shrink and increase the size of the array without copying all the elements?

**Comment by genaray** [comment]
> I don't understand how iterating over many small arrays is faster than a single large array. Or do you want to use chunks because then it's possible to shrink and increase the size of the array without copying all the elements?

The last statement is correct. When we spawn entities frequently a jagged array is way faster compared to one single array. And since thats a common case, i would prefer a jagged one. 

Iteration/acess wise jagged arrays may also perform slightly better or atleast similar. A 16kb bucket fits perfectly into the l1 cache at a time, one huge array would not fit into the cache and therefore there cache and page misses.

**Comment by moonheart08** [comment]
Also worth keeping in mind a world may go through many hundreds of thousands of entities if left running for a long time, and memory use shouldn't be affected significantly by 500,000 long deleted entities.

**Comment by Donaut** [comment]
@genaray  Do you want to mimic the behavior of a dictionary? For example, the Dictionary Add method will throw an exception if an item already exists with the same key.

**Comment by genaray** [comment]
> @genaray Do you want to mimic the behavior of a dictionary? For example, the Dictionary Add method will throw an exception if an item already exists with the same key.

Thats a good question :D What would you prefer? It probably kinda depends on the exact case.
E.g. there's a "JaggedArray" for "Arch.Extended", which has a `.Add` functionality since each bucket tracks the amount of used slots to be able to release unused Buckets later on : https://github.com/genaray/Arch.Extended/blob/master/Arch.LowLevel/Resources.cs

However that's a very rough implementation and nowhere near perfect. E.g. for an entity tracking jagged array a unsafe implementation would make the most sense to get rid of gc pressure ^^

**Comment by Donaut** [comment]
I rather not follow the dictionary behavior because some keys are cannot be handled (Negative ones.). Within a couple days I'm planning to push a pull request about it :D

**Comment by genaray** [comment]
Solved by @Donaut with #75 :)
